# Generated by Django 4.2.23 on 2025-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='previous_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
